// gRPC service contracts for the Synapse microservice split. Each domain service
// (auth, chat, message, presence, key directory) is exposed here so it can run as
// a standalone process; the gateway calls them as gRPC clients that satisfy the
// same Go interfaces the in-process services do (internal/gateway/services.go).
//
// Generated Go lands in internal/rpc/pb. Regenerate with:  make proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v7.34.1
// source: proto/synapse/v1/services.proto

// Distinct proto package from body.proto (synapse.v1): both are linked into the
// same binaries (the gateway/daemons use the wire bodies AND these RPCs), and a
// shared proto package + duplicate message names (e.g. KeyBundle) would collide
// in the global protobuf registry at init.

package rpcpb

import (
	reflect "reflect"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

func (x Op) Enum() *Op {
	p := new(Op)
	*p = x
	return p
}

func (x Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Op) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_synapse_v1_services_proto_enumTypes[0].Descriptor()
}

func (Op) Type() protoreflect.EnumType {
	return &file_proto_synapse_v1_services_proto_enumTypes[0]
}

func (x Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Op.Descriptor instead.
func (Op) EnumDescriptor() ([]byte, []int) {
	return file_proto_synapse_v1_services_proto_rawDescGZIP(), []int{0}
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_synapse_v1_services_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_services_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_services_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *User) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *User) GetAvatarRef() string {
	if x != nil {
		return x.AvatarRef
	}
	return ""
}

func (x *Session) Reset() {
	*x = Session{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_synapse_v1_services_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_services_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_services_proto_rawDescGZIP(), []int{1}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Session) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Session) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Session) GetResumeToken() string {
	if x != nil {
		return x.ResumeToken
	}
	return ""
}

func (x *Session) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Session) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *Session) GetRevokedAt() int64 {
	if x != nil {
		return x.RevokedAt
	}
	return 0
}

func (x *Chat) Reset() {
	*x = Chat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_synapse_v1_services_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_services_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_services_proto_rawDescGZIP(), []int{2}
}

func (x *Chat) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Chat) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Chat) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Chat) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Chat) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Chat) GetLastSeq() uint64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

func (x *Chat) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ChatMember) Reset() {
	*x = ChatMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_synapse_v1_services_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMember) ProtoMessage() {}

func (x *ChatMember) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_services_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMember.ProtoReflect.Descriptor instead.
func (*ChatMember) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_services_proto_rawDescGZIP(), []int{3}
}

func (x *ChatMember) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ChatMember) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChatMember) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMember) GetJoinedAt() int64 {
	if x != nil {
		return x.JoinedAt
	}
	return 0
}

func (x *ChatMember) GetMuted() bool {
	if x != nil {
		return x.Muted
	}
	return false
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_synapse_v1_services_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_services_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_services_proto_rawDescGZIP(), []int{4}
}

func (x *Attachment) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Attachment) GetMediaRef() string {
	if x != nil {
		return x.MediaRef
	}
	return ""
}

func (x *Attachment) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Attachment) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *Attachment) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Attachment) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *Attachment) GetWaveform() []int32 {
	if x != nil {
		return x.Waveform
	}
	return nil
}

func (x *Attachment) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Attachment) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Attachment) GetThumbRef() string {
	if x != nil {
		return x.ThumbRef
	}
	return ""
}

func (x *ForwardOrigin) Reset() {
	*x = ForwardOrigin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_synapse_v1_services_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForwardOrigin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardOrigin) ProtoMessage() {}

func (x *ForwardOrigin) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_services_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardOrigin.ProtoReflect.Descriptor instead.
func (*ForwardOrigin) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_services_proto_rawDescGZIP(), []int{5}
}

func (x *ForwardOrigin) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ForwardOrigin) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ForwardOrigin) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_synapse_v1_services_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_services_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_services_proto_rawDescGZIP(), []int{6}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *Message) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Message) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Message) GetMediaRef() string {
	if x != nil {
		return x.MediaRef
	}
	return ""
}

func (x *Message) GetReplyTo() string {
	if x != nil {
		return x.ReplyTo
	}
	return ""
}

func (x *Message) GetEdited() bool {
	if x != nil {
		return x.Edited
	}
	return false
}

func (x *Message) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *Message) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Message) GetEditedAt() int64 {
	if x != nil {
		return x.EditedAt
	}
	return 0
}

func (x *Message) GetAttachment() *Attachment {
	if x != nil {
		return x.Attachment
	}
	return nil
}

func (x *Message) GetThreadRoot() string {
	if x != nil {
		return x.ThreadRoot
	}
	return ""
}

func (x *Message) GetReplyCount() int32 {
	if x != nil {
		return x.ReplyCount
	}
	return 0
}

func (x *Message) GetForward() *ForwardOrigin {
	if x != nil {
		return x.Forward
	}
	return nil
}

func (x *Message) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_synapse_v1_services_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_services_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_services_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *RegisterRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RegisterRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_synapse_v1_services_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_services_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_services_proto_rawDescGZIP(), []int{8}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *LoginRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *SessionUser) Reset() {
	*x = SessionUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_synapse_v1_services_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionUser) ProtoMessage() {}

func (x *SessionUser) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_services_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionUser.ProtoReflect.Descriptor instead.
func (*SessionUser) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_services_proto_rawDescGZIP(), []int{9}
}

func (x *SessionUser) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *SessionUser) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *TokenRequest) Reset() {
	*x = TokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_synapse_v1_services_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRequest) ProtoMessage() {}

func (x *TokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_services_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRequest.ProtoReflect.Descriptor instead.
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_services_proto_rawDescGZIP(), []int{10}
}

func (x *TokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ResumeRequest) Reset() {
	*x = ResumeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_synapse_v1_services_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRequest) ProtoMessage() {}

func (x *ResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_services_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRequest.ProtoReflect.Descriptor instead.
func (*ResumeRequest) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_services_proto_rawDescGZIP(), []int{11}
}

func (x *ResumeRequest) GetResumeToken() string {
	if x != nil {
		return x.ResumeToken
	}
	return ""
}

func (x *Identity) Reset() {
	*x = Identity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_synapse_v1_services_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_services_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_services_proto_rawDescGZIP(), []int{12}
}

func (x *Identity) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *Identity) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *DirectRequest) Reset() {
	*x = DirectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_synapse_v1_services_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DirectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectRequest) ProtoMessage() {}

func (x *DirectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_services_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectRequest.ProtoReflect.Descriptor instead.
func (*DirectRequest) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_services_proto_rawDescGZIP(), []int{13}
}

func (x *DirectRequest) GetUserA() string {
	if x != nil {
		return x.UserA
	}
	return ""
}

func (x *DirectRequest) GetUserB() string {
	if x != nil {
		return x.UserB
	}
	return ""
}

func (x *ChatIDRequest) Reset() {
	*x = ChatIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_synapse_v1_services_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatIDRequest) ProtoMessage() {}

func (x *ChatIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_services_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatIDRequest.ProtoReflect.Descriptor instead.
func (*ChatIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_services_proto_rawDescGZIP(), []int{14}
}

func (x *ChatIDRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_synapse_v1_services_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_services_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_services_proto_rawDescGZIP(), []int{15}
}

func (x *CreateGroupRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CreateGroupRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateGroupRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateGroupRequest) GetMemberIds() []string {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

func (x *MembersReply) Reset() {
	*x = MembersReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_synapse_v1_services_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MembersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembersReply) ProtoMessage() {}

func (x *MembersReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_services_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembersReply.ProtoReflect.Descriptor instead.
func (*MembersReply) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_services_proto_rawDescGZIP(), []int{16}
}

func (x *MembersReply) GetMembers() []*ChatMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *MemberIDsReply) Reset() {
	*x = MemberIDsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_synapse_v1_services_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemberIDsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberIDsReply) ProtoMessage() {}

func (x *MemberIDsReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_services_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberIDsReply.ProtoReflect.Descriptor instead.
func (*MemberIDsReply) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_services_proto_rawDescGZIP(), []int{17}
}

func (x *MemberIDsReply) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *MemberPageRequest) Reset() {
	*x = MemberPageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_synapse_v1_services_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemberPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberPageRequest) ProtoMessage() {}

func (x *MemberPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_services_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberPageRequest.ProtoReflect.Descriptor instead.
func (*MemberPageRequest) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_services_proto_rawDescGZIP(), []int{18}
}

func (x *MemberPageRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *MemberPageRequest) GetAfterUserId() string {
	if x != nil {
		return x.AfterUserId
	}
	return ""
}

func (x *MemberPageRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ChatUserRequest) Reset() {
	*x = ChatUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_synapse_v1_services_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatUserRequest) ProtoMessage() {}

func (x *ChatUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_services_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatUserRequest.ProtoReflect.Descriptor instead.
func (*ChatUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_services_proto_rawDescGZIP(), []int{19}
}

func (x *ChatUserRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ChatUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BoolReply) Reset() {
	*x = BoolReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_synapse_v1_services_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoolReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolReply) ProtoMessage() {}

func (x *BoolReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_services_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolReply.ProtoReflect.Descriptor instead.
func (*BoolReply) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_services_proto_rawDescGZIP(), []int{20}
}

func (x *BoolReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *UserChatsRequest) Reset() {
	*x = UserChatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_synapse_v1_services_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserChatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserChatsRequest) ProtoMessage() {}

func (x *UserChatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_services_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserChatsRequest.ProtoReflect.Descriptor instead.
func (*UserChatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_services_proto_rawDescGZIP(), []int{21}
}

func (x *UserChatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserChatsRequest) GetAfter() string {
	if x != nil {
		return x.After
	}
	return ""
}

func (x *UserChatsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ChatSummary) Reset() {
	*x = ChatSummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_synapse_v1_services_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatSummary) ProtoMessage() {}

func (x *ChatSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_services_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatSummary.ProtoReflect.Descriptor instead.
func (*ChatSummary) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_services_proto_rawDescGZIP(), []int{22}
}

func (x *ChatSummary) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

func (x *ChatSummary) GetMyRole() string {
	if x != nil {
		return x.MyRole
	}
	return ""
}

func (x *ChatSummary) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *ChatSummariesReply) Reset() {
	*x = ChatSummariesReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_synapse_v1_services_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatSummariesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatSummariesReply) ProtoMessage() {}

func (x *ChatSummariesReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_services_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatSummariesReply.ProtoReflect.Descriptor instead.
func (*ChatSummariesReply) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_services_proto_rawDescGZIP(), []int{23}
}

func (x *ChatSummariesReply) GetChats() []*ChatSummary {
	if x != nil {
		return x.Chats
	}
	return nil
}

func (x *SubmitRequest) Reset() {
	*x = SubmitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_synapse_v1_services_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRequest) ProtoMessage() {}

func (x *SubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_services_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRequest.ProtoReflect.Descriptor instead.
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_services_proto_rawDescGZIP(), []int{24}
}

func (x *SubmitRequest) GetOp() Op {
	if x != nil {
		return x.Op
	}
	return Op_OP_UNSPECIFIED
}

func (x *SubmitRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *SubmitRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *SubmitRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SubmitRequest) GetDedupKey() string {
	if x != nil {
		return x.DedupKey
	}
	return ""
}

func (x *SubmitRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SubmitRequest) GetMediaRef() string {
	if x != nil {
		return x.MediaRef
	}
	return ""
}

func (x *SubmitRequest) GetReplyTo() string {
	if x != nil {
		return x.ReplyTo
	}
	return ""
}

func (x *SubmitRequest) GetAttachment() *Attachment {
	if x != nil {
		return x.Attachment
	}
	return nil
}

func (x *SubmitRequest) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *SubmitReply) Reset() {
	*x = SubmitReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_synapse_v1_services_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitReply) ProtoMessage() {}

func (x *SubmitReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_services_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitReply.ProtoReflect.Descriptor instead.
func (*SubmitReply) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_services_proto_rawDescGZIP(), []int{25}
}

func (x *SubmitReply) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SubmitReply) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

func (x *HistoryRequest) Reset() {
	*x = HistoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_synapse_v1_services_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRequest) ProtoMessage() {}

func (x *HistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_services_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRequest.ProtoReflect.Descriptor instead.
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_services_proto_rawDescGZIP(), []int{26}
}

func (x *HistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *HistoryRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *HistoryRequest) GetBeforeSeq() uint64 {
	if x != nil {
		return x.BeforeSeq
	}
	return 0
}

func (x *HistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *HistoryReply) Reset() {
	*x = HistoryReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_synapse_v1_services_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HistoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryReply) ProtoMessage() {}

func (x *HistoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_services_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryReply.ProtoReflect.Descriptor instead.
func (*HistoryReply) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_services_proto_rawDescGZIP(), []int{27}
}

func (x *HistoryReply) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ThreadRequest) Reset() {
	*x = ThreadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_synapse_v1_services_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadRequest) ProtoMessage() {}

func (x *ThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_services_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadRequest.ProtoReflect.Descriptor instead.
func (*ThreadRequest) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_services_proto_rawDescGZIP(), []int{28}
}

func (x *ThreadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ThreadRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ThreadRequest) GetRootId() string {
	if x != nil {
		return x.RootId
	}
	return ""
}

func (x *ThreadRequest) GetAfterSeq() uint64 {
	if x != nil {
		return x.AfterSeq
	}
	return 0
}

func (x *ThreadRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ForwardRequest) Reset() {
	*x = ForwardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_synapse_v1_services_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardRequest) ProtoMessage() {}

func (x *ForwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_services_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardRequest.ProtoReflect.Descriptor instead.
func (*ForwardRequest) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_services_proto_rawDescGZIP(), []int{29}
}

func (x *ForwardRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ForwardRequest) GetSrcChatId() string {
	if x != nil {
		return x.SrcChatId
	}
	return ""
}

func (x *ForwardRequest) GetSrcMsgId() string {
	if x != nil {
		return x.SrcMsgId
	}
	return ""
}

func (x *ForwardRequest) GetDstChatId() string {
	if x != nil {
		return x.DstChatId
	}
	return ""
}

func (x *ForwardRequest) GetDedupKey() string {
	if x != nil {
		return x.DedupKey
	}
	return ""
}

func (x *MarkReadRequest) Reset() {
	*x = MarkReadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_synapse_v1_services_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarkReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadRequest) ProtoMessage() {}

func (x *MarkReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_services_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadRequest.ProtoReflect.Descriptor instead.
func (*MarkReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_services_proto_rawDescGZIP(), []int{30}
}

func (x *MarkReadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MarkReadRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *MarkReadRequest) GetUpToSeq() uint64 {
	if x != nil {
		return x.UpToSeq
	}
	return 0
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_synapse_v1_services_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_services_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_services_proto_rawDescGZIP(), []int{31}
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_synapse_v1_services_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_services_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_services_proto_rawDescGZIP(), []int{32}
}

func (x *UserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TypingRequest) Reset() {
	*x = TypingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_synapse_v1_services_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TypingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypingRequest) ProtoMessage() {}

func (x *TypingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_services_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypingRequest.ProtoReflect.Descriptor instead.
func (*TypingRequest) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_services_proto_rawDescGZIP(), []int{33}
}

func (x *TypingRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *TypingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TypingRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_synapse_v1_services_proto_msgTypes[34]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_services_proto_msgTypes[34]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_services_proto_rawDescGZIP(), []int{34}
}

func (x *PublishRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PublishRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *PublishRequest) GetIdentityKey() string {
	if x != nil {
		return x.IdentityKey
	}
	return ""
}

func (x *PublishRequest) GetSigningKey() string {
	if x != nil {
		return x.SigningKey
	}
	return ""
}

func (x *PublishRequest) GetSignedPrekey() string {
	if x != nil {
		return x.SignedPrekey
	}
	return ""
}

func (x *PublishRequest) GetSignedPrekeySig() string {
	if x != nil {
		return x.SignedPrekeySig
	}
	return ""
}

func (x *PublishRequest) GetPrekeys() []string {
	if x != nil {
		return x.Prekeys
	}
	return nil
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_synapse_v1_services_proto_msgTypes[35]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_services_proto_msgTypes[35]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_services_proto_rawDescGZIP(), []int{35}
}

func (x *FetchRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FetchRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *KeyBundle) Reset() {
	*x = KeyBundle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_synapse_v1_services_proto_msgTypes[36]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyBundle) ProtoMessage() {}

func (x *KeyBundle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_services_proto_msgTypes[36]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyBundle.ProtoReflect.Descriptor instead.
func (*KeyBundle) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_services_proto_rawDescGZIP(), []int{36}
}

func (x *KeyBundle) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *KeyBundle) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *KeyBundle) GetIdentityKey() string {
	if x != nil {
		return x.IdentityKey
	}
	return ""
}

func (x *KeyBundle) GetSigningKey() string {
	if x != nil {
		return x.SigningKey
	}
	return ""
}

func (x *KeyBundle) GetSignedPrekey() string {
	if x != nil {
		return x.SignedPrekey
	}
	return ""
}

func (x *KeyBundle) GetSignedPrekeySig() string {
	if x != nil {
		return x.SignedPrekeySig
	}
	return ""
}

func (x *KeyBundle) GetOneTimePrekey() string {
	if x != nil {
		return x.OneTimePrekey
	}
	return ""
}

func (x *FetchReply) Reset() {
	*x = FetchReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_synapse_v1_services_proto_msgTypes[37]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchReply) ProtoMessage() {}

func (x *FetchReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_services_proto_msgTypes[37]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchReply.ProtoReflect.Descriptor instead.
func (*FetchReply) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_services_proto_rawDescGZIP(), []int{37}
}

func (x *FetchReply) GetBundle() *KeyBundle {
	if x != nil {
		return x.Bundle
	}
	return nil
}

func (x *FetchReply) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *FetchAllReply) Reset() {
	*x = FetchAllReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_synapse_v1_services_proto_msgTypes[38]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchAllReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchAllReply) ProtoMessage() {}

func (x *FetchAllReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_synapse_v1_services_proto_msgTypes[38]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchAllReply.ProtoReflect.Descriptor instead.
func (*FetchAllReply) Descriptor() ([]byte, []int) {
	return file_proto_synapse_v1_services_proto_rawDescGZIP(), []int{38}
}

func (x *FetchAllReply) GetBundles() []*KeyBundle {
	if x != nil {
		return x.Bundles
	}
	return nil
}

func file_proto_synapse_v1_services_proto_rawDescGZIP() []byte {
	file_proto_synapse_v1_services_proto_rawDescOnce.Do(func() {
		file_proto_synapse_v1_services_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_synapse_v1_services_proto_rawDescData)
	})
	return file_proto_synapse_v1_services_proto_rawDescData
}

func init() { file_proto_synapse_v1_services_proto_init() }

func file_proto_synapse_v1_services_proto_init() {
	if File_proto_synapse_v1_services_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_synapse_v1_services_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_synapse_v1_services_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Session); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_synapse_v1_services_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Chat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_synapse_v1_services_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ChatMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_synapse_v1_services_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Attachment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_synapse_v1_services_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ForwardOrigin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_synapse_v1_services_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_synapse_v1_services_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*RegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_synapse_v1_services_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*LoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_synapse_v1_services_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*SessionUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_synapse_v1_services_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*TokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_synapse_v1_services_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*ResumeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_synapse_v1_services_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*Identity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_synapse_v1_services_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*DirectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_synapse_v1_services_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*ChatIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_synapse_v1_services_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*CreateGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_synapse_v1_services_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*MembersReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_synapse_v1_services_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*MemberIDsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_synapse_v1_services_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*MemberPageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_synapse_v1_services_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*ChatUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_synapse_v1_services_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*BoolReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_synapse_v1_services_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*UserChatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_synapse_v1_services_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*ChatSummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_synapse_v1_services_proto_msgTypes[23].Exporter = func(v any, i int) any {
			switch v := v.(*ChatSummariesReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_synapse_v1_services_proto_msgTypes[24].Exporter = func(v any, i int) any {
			switch v := v.(*SubmitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_synapse_v1_services_proto_msgTypes[25].Exporter = func(v any, i int) any {
			switch v := v.(*SubmitReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_synapse_v1_services_proto_msgTypes[26].Exporter = func(v any, i int) any {
			switch v := v.(*HistoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_synapse_v1_services_proto_msgTypes[27].Exporter = func(v any, i int) any {
			switch v := v.(*HistoryReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_synapse_v1_services_proto_msgTypes[28].Exporter = func(v any, i int) any {
			switch v := v.(*ThreadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_synapse_v1_services_proto_msgTypes[29].Exporter = func(v any, i int) any {
			switch v := v.(*ForwardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_synapse_v1_services_proto_msgTypes[30].Exporter = func(v any, i int) any {
			switch v := v.(*MarkReadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_synapse_v1_services_proto_msgTypes[31].Exporter = func(v any, i int) any {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_synapse_v1_services_proto_msgTypes[32].Exporter = func(v any, i int) any {
			switch v := v.(*UserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_synapse_v1_services_proto_msgTypes[33].Exporter = func(v any, i int) any {
			switch v := v.(*TypingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_synapse_v1_services_proto_msgTypes[34].Exporter = func(v any, i int) any {
			switch v := v.(*PublishRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_synapse_v1_services_proto_msgTypes[35].Exporter = func(v any, i int) any {
			switch v := v.(*FetchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_synapse_v1_services_proto_msgTypes[36].Exporter = func(v any, i int) any {
			switch v := v.(*KeyBundle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_synapse_v1_services_proto_msgTypes[37].Exporter = func(v any, i int) any {
			switch v := v.(*FetchReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_synapse_v1_services_proto_msgTypes[38].Exporter = func(v any, i int) any {
			switch v := v.(*FetchAllReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_synapse_v1_services_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_proto_synapse_v1_services_proto_goTypes,
		DependencyIndexes: file_proto_synapse_v1_services_proto_depIdxs,
		EnumInfos:         file_proto_synapse_v1_services_proto_enumTypes,
		MessageInfos:      file_proto_synapse_v1_services_proto_msgTypes,
	}.Build()
	File_proto_synapse_v1_services_proto = out.File
	file_proto_synapse_v1_services_proto_rawDesc = nil
	file_proto_synapse_v1_services_proto_goTypes = nil
	file_proto_synapse_v1_services_proto_depIdxs = nil
}
