// gRPC service contracts for the SyncApp microservice split. Each domain service
// (auth, chat, message, presence, key directory) is exposed here so it can run as
// a standalone process; the gateway calls them as gRPC clients that satisfy the
// same Go interfaces the in-process services do (internal/gateway/services.go).
//
// Generated Go lands in internal/rpc/pb. Regenerate with:  make proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v7.35.1
// source: proto/syncapp/v1/services.proto

// Distinct proto package from body.proto (syncapp.v1): both are linked into the
// same binaries (the gateway/daemons use the wire bodies AND these RPCs), and a
// shared proto package + duplicate message names (e.g. KeyBundle) would collide
// in the global protobuf registry at init.

package rpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

func (x Op) Enum() *Op {
	p := new(Op)
	*p = x
	return p
}

func (x Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Op) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_syncapp_v1_services_proto_enumTypes[0].Descriptor()
}

func (Op) Type() protoreflect.EnumType {
	return &file_proto_syncapp_v1_services_proto_enumTypes[0]
}

func (x Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Op.Descriptor instead.
func (Op) EnumDescriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{0}
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *User) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *User) GetAvatarRef() string {
	if x != nil {
		return x.AvatarRef
	}
	return ""
}

func (x *User) GetPrivacyLastSeen() string {
	if x != nil {
		return x.PrivacyLastSeen
	}
	return ""
}

func (x *User) GetPrivacyAvatar() string {
	if x != nil {
		return x.PrivacyAvatar
	}
	return ""
}

func (x *User) GetPrivacyGroups() string {
	if x != nil {
		return x.PrivacyGroups
	}
	return ""
}

func (x *User) GetPrivacyPushPreview() bool {
	if x != nil {
		return x.PrivacyPushPreview
	}
	return false
}

func (x *Session) Reset() {
	*x = Session{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{1}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Session) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Session) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Session) GetResumeToken() string {
	if x != nil {
		return x.ResumeToken
	}
	return ""
}

func (x *Session) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Session) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *Session) GetRevokedAt() int64 {
	if x != nil {
		return x.RevokedAt
	}
	return 0
}

func (x *Session) GetPrevResumeToken() string {
	if x != nil {
		return x.PrevResumeToken
	}
	return ""
}

func (x *Session) GetResumeRotatedAt() int64 {
	if x != nil {
		return x.ResumeRotatedAt
	}
	return 0
}

func (x *Chat) Reset() {
	*x = Chat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{2}
}

func (x *Chat) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Chat) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Chat) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Chat) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Chat) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Chat) GetLastSeq() uint64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

func (x *Chat) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ChatMember) Reset() {
	*x = ChatMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMember) ProtoMessage() {}

func (x *ChatMember) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMember.ProtoReflect.Descriptor instead.
func (*ChatMember) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{3}
}

func (x *ChatMember) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ChatMember) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChatMember) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMember) GetJoinedAt() int64 {
	if x != nil {
		return x.JoinedAt
	}
	return 0
}

func (x *ChatMember) GetMuted() bool {
	if x != nil {
		return x.Muted
	}
	return false
}

func (x *ChatMember) GetMutedUntil() int64 {
	if x != nil {
		return x.MutedUntil
	}
	return 0
}

func (x *ChatMember) GetPinned() bool {
	if x != nil {
		return x.Pinned
	}
	return false
}

func (x *ChatMember) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

// Attachment and ForwardOrigin mirror their body.proto twins field for field.
// They are redeclared rather than imported because the two files are deliberately
// separate proto packages (see the note at the top): the shapes are the same
// domain types crossing a different boundary — service-to-service, not
// client-to-server.

func (x *Attachment) Reset() {
	*x = Attachment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{4}
}

func (x *Attachment) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Attachment) GetMediaRef() string {
	if x != nil {
		return x.MediaRef
	}
	return ""
}

func (x *Attachment) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Attachment) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *Attachment) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Attachment) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *Attachment) GetWaveform() []int32 {
	if x != nil {
		return x.Waveform
	}
	return nil
}

func (x *Attachment) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Attachment) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Attachment) GetThumbRef() string {
	if x != nil {
		return x.ThumbRef
	}
	return ""
}

func (x *ForwardOrigin) Reset() {
	*x = ForwardOrigin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForwardOrigin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardOrigin) ProtoMessage() {}

func (x *ForwardOrigin) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardOrigin.ProtoReflect.Descriptor instead.
func (*ForwardOrigin) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{5}
}

func (x *ForwardOrigin) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ForwardOrigin) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ForwardOrigin) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

// Message must carry EVERY field a client can observe: the gateway renders its
// wire body straight from this, so a field missing here is a field no client on
// the split deployment can ever see — even though the monolith shows it.

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{6}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *Message) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Message) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Message) GetMediaRef() string {
	if x != nil {
		return x.MediaRef
	}
	return ""
}

func (x *Message) GetReplyTo() string {
	if x != nil {
		return x.ReplyTo
	}
	return ""
}

func (x *Message) GetEdited() bool {
	if x != nil {
		return x.Edited
	}
	return false
}

func (x *Message) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *Message) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Message) GetEditedAt() int64 {
	if x != nil {
		return x.EditedAt
	}
	return 0
}

func (x *Message) GetAttachment() *Attachment {
	if x != nil {
		return x.Attachment
	}
	return nil
}

func (x *Message) GetThreadRoot() string {
	if x != nil {
		return x.ThreadRoot
	}
	return ""
}

func (x *Message) GetReplyCount() int32 {
	if x != nil {
		return x.ReplyCount
	}
	return 0
}

func (x *Message) GetForward() *ForwardOrigin {
	if x != nil {
		return x.Forward
	}
	return nil
}

func (x *Message) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *RegisterRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RegisterRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{8}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *LoginRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *SessionUser) Reset() {
	*x = SessionUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionUser) ProtoMessage() {}

func (x *SessionUser) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionUser.ProtoReflect.Descriptor instead.
func (*SessionUser) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{9}
}

func (x *SessionUser) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *SessionUser) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *TokenRequest) Reset() {
	*x = TokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRequest) ProtoMessage() {}

func (x *TokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRequest.ProtoReflect.Descriptor instead.
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{10}
}

func (x *TokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ResumeRequest) Reset() {
	*x = ResumeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRequest) ProtoMessage() {}

func (x *ResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRequest.ProtoReflect.Descriptor instead.
func (*ResumeRequest) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{11}
}

func (x *ResumeRequest) GetResumeToken() string {
	if x != nil {
		return x.ResumeToken
	}
	return ""
}

func (x *Identity) Reset() {
	*x = Identity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{12}
}

func (x *Identity) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *Identity) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// Session management and account deletion. These exist on the gRPC contract and
// not only on the local service because the gateway talks to ONE interface: a
// capability that is present in the monolith and absent behind gRPC is a feature
// that silently disappears when someone enables the split, which is the topology
// drift the risk register already names.

func (x *UserIDRequest) Reset() {
	*x = UserIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIDRequest) ProtoMessage() {}

func (x *UserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIDRequest.ProtoReflect.Descriptor instead.
func (*UserIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{13}
}

func (x *UserIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SessionRow) Reset() {
	*x = SessionRow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRow) ProtoMessage() {}

func (x *SessionRow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRow.ProtoReflect.Descriptor instead.
func (*SessionRow) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{14}
}

func (x *SessionRow) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionRow) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SessionRow) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SessionRow) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SessionRow) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *SessionRow) GetRevokedAt() int64 {
	if x != nil {
		return x.RevokedAt
	}
	return 0
}

func (x *SessionsReply) Reset() {
	*x = SessionsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionsReply) ProtoMessage() {}

func (x *SessionsReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionsReply.ProtoReflect.Descriptor instead.
func (*SessionsReply) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{15}
}

func (x *SessionsReply) GetSessions() []*SessionRow {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *RevokeOwnedRequest) Reset() {
	*x = RevokeOwnedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevokeOwnedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeOwnedRequest) ProtoMessage() {}

func (x *RevokeOwnedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeOwnedRequest.ProtoReflect.Descriptor instead.
func (*RevokeOwnedRequest) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{16}
}

func (x *RevokeOwnedRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RevokeOwnedRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RevokeAllRequest) Reset() {
	*x = RevokeAllRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevokeAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAllRequest) ProtoMessage() {}

func (x *RevokeAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAllRequest.ProtoReflect.Descriptor instead.
func (*RevokeAllRequest) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{17}
}

func (x *RevokeAllRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RevokeAllRequest) GetKeepSessionId() string {
	if x != nil {
		return x.KeepSessionId
	}
	return ""
}

func (x *RevokeAllReply) Reset() {
	*x = RevokeAllReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevokeAllReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAllReply) ProtoMessage() {}

func (x *RevokeAllReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAllReply.ProtoReflect.Descriptor instead.
func (*RevokeAllReply) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{18}
}

func (x *RevokeAllReply) GetRevoked() int32 {
	if x != nil {
		return x.Revoked
	}
	return 0
}

func (x *DeleteAccountRequest) Reset() {
	*x = DeleteAccountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountRequest) ProtoMessage() {}

func (x *DeleteAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteAccountRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteAccountRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// LoginWithCodeRequest is LoginRequest plus the second factor. A separate message
// rather than an extra field on LoginRequest, so the existing call keeps its exact
// meaning for any caller that has not moved.

func (x *LoginWithCodeRequest) Reset() {
	*x = LoginWithCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginWithCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginWithCodeRequest) ProtoMessage() {}

func (x *LoginWithCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginWithCodeRequest.ProtoReflect.Descriptor instead.
func (*LoginWithCodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{20}
}

func (x *LoginWithCodeRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginWithCodeRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginWithCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *LoginWithCodeRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *LoginWithCodeRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{21}
}

func (x *ChangePasswordRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChangePasswordRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetKeepSessionId() string {
	if x != nil {
		return x.KeepSessionId
	}
	return ""
}

func (x *ChangePasswordReply) Reset() {
	*x = ChangePasswordReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangePasswordReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordReply) ProtoMessage() {}

func (x *ChangePasswordReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordReply.ProtoReflect.Descriptor instead.
func (*ChangePasswordReply) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{22}
}

func (x *ChangePasswordReply) GetSessionsRevoked() int32 {
	if x != nil {
		return x.SessionsRevoked
	}
	return 0
}

func (x *BeginTOTPRequest) Reset() {
	*x = BeginTOTPRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeginTOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginTOTPRequest) ProtoMessage() {}

func (x *BeginTOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginTOTPRequest.ProtoReflect.Descriptor instead.
func (*BeginTOTPRequest) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{23}
}

func (x *BeginTOTPRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BeginTOTPRequest) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *BeginTOTPReply) Reset() {
	*x = BeginTOTPReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeginTOTPReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginTOTPReply) ProtoMessage() {}

func (x *BeginTOTPReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginTOTPReply.ProtoReflect.Descriptor instead.
func (*BeginTOTPReply) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{24}
}

func (x *BeginTOTPReply) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *BeginTOTPReply) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *ConfirmTOTPRequest) Reset() {
	*x = ConfirmTOTPRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmTOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmTOTPRequest) ProtoMessage() {}

func (x *ConfirmTOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmTOTPRequest.ProtoReflect.Descriptor instead.
func (*ConfirmTOTPRequest) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{25}
}

func (x *ConfirmTOTPRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ConfirmTOTPRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// The recovery codes, returned once. The stored form is a hash, so there is
// nothing to return later.

func (x *ConfirmTOTPReply) Reset() {
	*x = ConfirmTOTPReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmTOTPReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmTOTPReply) ProtoMessage() {}

func (x *ConfirmTOTPReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmTOTPReply.ProtoReflect.Descriptor instead.
func (*ConfirmTOTPReply) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{26}
}

func (x *ConfirmTOTPReply) GetRecoveryCodes() []string {
	if x != nil {
		return x.RecoveryCodes
	}
	return nil
}

func (x *DisableTOTPRequest) Reset() {
	*x = DisableTOTPRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisableTOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableTOTPRequest) ProtoMessage() {}

func (x *DisableTOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableTOTPRequest.ProtoReflect.Descriptor instead.
func (*DisableTOTPRequest) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{27}
}

func (x *DisableTOTPRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DisableTOTPRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *DisableTOTPRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *TwoFactorStateReply) Reset() {
	*x = TwoFactorStateReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TwoFactorStateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwoFactorStateReply) ProtoMessage() {}

func (x *TwoFactorStateReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwoFactorStateReply.ProtoReflect.Descriptor instead.
func (*TwoFactorStateReply) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{28}
}

func (x *TwoFactorStateReply) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *TwoFactorStateReply) GetRecoveryLeft() int32 {
	if x != nil {
		return x.RecoveryLeft
	}
	return 0
}

func (x *DirectRequest) Reset() {
	*x = DirectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DirectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectRequest) ProtoMessage() {}

func (x *DirectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectRequest.ProtoReflect.Descriptor instead.
func (*DirectRequest) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{29}
}

func (x *DirectRequest) GetUserA() string {
	if x != nil {
		return x.UserA
	}
	return ""
}

func (x *DirectRequest) GetUserB() string {
	if x != nil {
		return x.UserB
	}
	return ""
}

func (x *ChatIDRequest) Reset() {
	*x = ChatIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatIDRequest) ProtoMessage() {}

func (x *ChatIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatIDRequest.ProtoReflect.Descriptor instead.
func (*ChatIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{30}
}

func (x *ChatIDRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{31}
}

func (x *CreateGroupRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CreateGroupRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateGroupRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateGroupRequest) GetMemberIds() []string {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

func (x *MembersReply) Reset() {
	*x = MembersReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MembersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembersReply) ProtoMessage() {}

func (x *MembersReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembersReply.ProtoReflect.Descriptor instead.
func (*MembersReply) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{32}
}

func (x *MembersReply) GetMembers() []*ChatMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *MemberIDsReply) Reset() {
	*x = MemberIDsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemberIDsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberIDsReply) ProtoMessage() {}

func (x *MemberIDsReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberIDsReply.ProtoReflect.Descriptor instead.
func (*MemberIDsReply) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{33}
}

func (x *MemberIDsReply) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

// MemberPageRequest walks membership by keyset: ids after `after_user_id`,
// ordered, at most `limit`. Fanout needs this to stream a million-member channel
// instead of materializing it.

func (x *MemberPageRequest) Reset() {
	*x = MemberPageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[34]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemberPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberPageRequest) ProtoMessage() {}

func (x *MemberPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[34]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberPageRequest.ProtoReflect.Descriptor instead.
func (*MemberPageRequest) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{34}
}

func (x *MemberPageRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *MemberPageRequest) GetAfterUserId() string {
	if x != nil {
		return x.AfterUserId
	}
	return ""
}

func (x *MemberPageRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ChatUserRequest) Reset() {
	*x = ChatUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[35]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatUserRequest) ProtoMessage() {}

func (x *ChatUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[35]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatUserRequest.ProtoReflect.Descriptor instead.
func (*ChatUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{35}
}

func (x *ChatUserRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ChatUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BoolReply) Reset() {
	*x = BoolReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[36]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoolReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolReply) ProtoMessage() {}

func (x *BoolReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[36]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolReply.ProtoReflect.Descriptor instead.
func (*BoolReply) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{36}
}

func (x *BoolReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// CountReply carries a plain tally. Its own message rather than reusing an
// existing reply, because a count is not a boolean and squeezing it into one
// would lose the number the caller actually needs.

func (x *CountReply) Reset() {
	*x = CountReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[37]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountReply) ProtoMessage() {}

func (x *CountReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[37]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountReply.ProtoReflect.Descriptor instead.
func (*CountReply) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{37}
}

func (x *CountReply) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *PinnedCountRequest) Reset() {
	*x = PinnedCountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[38]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PinnedCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinnedCountRequest) ProtoMessage() {}

func (x *PinnedCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[38]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinnedCountRequest.ProtoReflect.Descriptor instead.
func (*PinnedCountRequest) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{38}
}

func (x *PinnedCountRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PinnedCountRequest) GetExceptChatId() string {
	if x != nil {
		return x.ExceptChatId
	}
	return ""
}

// UserChatsRequest pages a user's chat list by keyset over the chat id. The
// whole summary is built inside the chat service: assembling it at the gateway
// would cost one Get (plus one Members for every direct chat) per row, turning
// one screen of chats into a burst of round trips.

func (x *UserChatsRequest) Reset() {
	*x = UserChatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[39]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserChatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserChatsRequest) ProtoMessage() {}

func (x *UserChatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[39]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserChatsRequest.ProtoReflect.Descriptor instead.
func (*UserChatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{39}
}

func (x *UserChatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserChatsRequest) GetAfter() string {
	if x != nil {
		return x.After
	}
	return ""
}

func (x *UserChatsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *UserChatPageRequest) Reset() {
	*x = UserChatPageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[40]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserChatPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserChatPageRequest) ProtoMessage() {}

func (x *UserChatPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[40]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserChatPageRequest.ProtoReflect.Descriptor instead.
func (*UserChatPageRequest) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{40}
}

func (x *UserChatPageRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserChatPageRequest) GetAfter() string {
	if x != nil {
		return x.After
	}
	return ""
}

func (x *UserChatPageRequest) GetAfterActivity() int64 {
	if x != nil {
		return x.AfterActivity
	}
	return 0
}

func (x *UserChatPageRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *UserChatPageRequest) GetIncludeArchived() bool {
	if x != nil {
		return x.IncludeArchived
	}
	return false
}

func (x *SetChatFlagsRequest) Reset() {
	*x = SetChatFlagsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[41]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetChatFlagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetChatFlagsRequest) ProtoMessage() {}

func (x *SetChatFlagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[41]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetChatFlagsRequest.ProtoReflect.Descriptor instead.
func (*SetChatFlagsRequest) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{41}
}

func (x *SetChatFlagsRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *SetChatFlagsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetChatFlagsRequest) GetMutedUntil() int64 {
	if x != nil {
		return x.MutedUntil
	}
	return 0
}

func (x *SetChatFlagsRequest) GetPinned() bool {
	if x != nil {
		return x.Pinned
	}
	return false
}

func (x *SetChatFlagsRequest) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

func (x *ChatFlagsReply) Reset() {
	*x = ChatFlagsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[42]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatFlagsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatFlagsReply) ProtoMessage() {}

func (x *ChatFlagsReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[42]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatFlagsReply.ProtoReflect.Descriptor instead.
func (*ChatFlagsReply) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{42}
}

func (x *ChatFlagsReply) GetMutedUntil() int64 {
	if x != nil {
		return x.MutedUntil
	}
	return 0
}

func (x *ChatFlagsReply) GetPinned() bool {
	if x != nil {
		return x.Pinned
	}
	return false
}

func (x *ChatFlagsReply) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

func (x *ChatSummary) Reset() {
	*x = ChatSummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[43]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatSummary) ProtoMessage() {}

func (x *ChatSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[43]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatSummary.ProtoReflect.Descriptor instead.
func (*ChatSummary) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{43}
}

func (x *ChatSummary) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

func (x *ChatSummary) GetMyRole() string {
	if x != nil {
		return x.MyRole
	}
	return ""
}

func (x *ChatSummary) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *ChatSummary) GetLastMessage() *Message {
	if x != nil {
		return x.LastMessage
	}
	return nil
}

func (x *ChatSummary) GetUnreadCount() int64 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

func (x *ChatSummary) GetLastActivityAt() int64 {
	if x != nil {
		return x.LastActivityAt
	}
	return 0
}

func (x *ChatSummary) GetMutedUntil() int64 {
	if x != nil {
		return x.MutedUntil
	}
	return 0
}

func (x *ChatSummary) GetPinned() bool {
	if x != nil {
		return x.Pinned
	}
	return false
}

func (x *ChatSummary) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

// ChatSummariesReply is one page of summaries. The cursor is not repeated here:
// it is the id of the last row, so the gateway derives it from the page itself
// and the monolith and the split deployment cannot disagree about it.

func (x *ChatSummariesReply) Reset() {
	*x = ChatSummariesReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[44]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatSummariesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatSummariesReply) ProtoMessage() {}

func (x *ChatSummariesReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[44]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatSummariesReply.ProtoReflect.Descriptor instead.
func (*ChatSummariesReply) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{44}
}

func (x *ChatSummariesReply) GetChats() []*ChatSummary {
	if x != nil {
		return x.Chats
	}
	return nil
}

func (x *SubmitRequest) Reset() {
	*x = SubmitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[45]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRequest) ProtoMessage() {}

func (x *SubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[45]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRequest.ProtoReflect.Descriptor instead.
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{45}
}

func (x *SubmitRequest) GetOp() Op {
	if x != nil {
		return x.Op
	}
	return Op_OP_UNSPECIFIED
}

func (x *SubmitRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *SubmitRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *SubmitRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SubmitRequest) GetDedupKey() string {
	if x != nil {
		return x.DedupKey
	}
	return ""
}

func (x *SubmitRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SubmitRequest) GetMediaRef() string {
	if x != nil {
		return x.MediaRef
	}
	return ""
}

func (x *SubmitRequest) GetReplyTo() string {
	if x != nil {
		return x.ReplyTo
	}
	return ""
}

func (x *SubmitRequest) GetAttachment() *Attachment {
	if x != nil {
		return x.Attachment
	}
	return nil
}

func (x *SubmitRequest) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *SubmitReply) Reset() {
	*x = SubmitReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[46]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitReply) ProtoMessage() {}

func (x *SubmitReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[46]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitReply.ProtoReflect.Descriptor instead.
func (*SubmitReply) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{46}
}

func (x *SubmitReply) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SubmitReply) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

func (x *HistoryRequest) Reset() {
	*x = HistoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[47]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRequest) ProtoMessage() {}

func (x *HistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[47]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRequest.ProtoReflect.Descriptor instead.
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{47}
}

func (x *HistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *HistoryRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *HistoryRequest) GetBeforeSeq() uint64 {
	if x != nil {
		return x.BeforeSeq
	}
	return 0
}

func (x *HistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *HistoryReply) Reset() {
	*x = HistoryReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[48]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HistoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryReply) ProtoMessage() {}

func (x *HistoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[48]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryReply.ProtoReflect.Descriptor instead.
func (*HistoryReply) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{48}
}

func (x *HistoryReply) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ThreadRequest) Reset() {
	*x = ThreadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[49]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadRequest) ProtoMessage() {}

func (x *ThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[49]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadRequest.ProtoReflect.Descriptor instead.
func (*ThreadRequest) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{49}
}

func (x *ThreadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ThreadRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ThreadRequest) GetRootId() string {
	if x != nil {
		return x.RootId
	}
	return ""
}

func (x *ThreadRequest) GetAfterSeq() uint64 {
	if x != nil {
		return x.AfterSeq
	}
	return 0
}

func (x *ThreadRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ForwardRequest) Reset() {
	*x = ForwardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[50]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardRequest) ProtoMessage() {}

func (x *ForwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[50]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardRequest.ProtoReflect.Descriptor instead.
func (*ForwardRequest) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{50}
}

func (x *ForwardRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ForwardRequest) GetSrcChatId() string {
	if x != nil {
		return x.SrcChatId
	}
	return ""
}

func (x *ForwardRequest) GetSrcMsgId() string {
	if x != nil {
		return x.SrcMsgId
	}
	return ""
}

func (x *ForwardRequest) GetDstChatId() string {
	if x != nil {
		return x.DstChatId
	}
	return ""
}

func (x *ForwardRequest) GetDedupKey() string {
	if x != nil {
		return x.DedupKey
	}
	return ""
}

func (x *MarkReadRequest) Reset() {
	*x = MarkReadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[51]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarkReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadRequest) ProtoMessage() {}

func (x *MarkReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[51]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadRequest.ProtoReflect.Descriptor instead.
func (*MarkReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{51}
}

func (x *MarkReadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MarkReadRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *MarkReadRequest) GetUpToSeq() uint64 {
	if x != nil {
		return x.UpToSeq
	}
	return 0
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[52]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[52]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{52}
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[53]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[53]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{53}
}

func (x *UserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TypingRequest) Reset() {
	*x = TypingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[54]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TypingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypingRequest) ProtoMessage() {}

func (x *TypingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[54]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypingRequest.ProtoReflect.Descriptor instead.
func (*TypingRequest) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{54}
}

func (x *TypingRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *TypingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TypingRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[55]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[55]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{55}
}

func (x *PublishRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PublishRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *PublishRequest) GetIdentityKey() string {
	if x != nil {
		return x.IdentityKey
	}
	return ""
}

func (x *PublishRequest) GetSigningKey() string {
	if x != nil {
		return x.SigningKey
	}
	return ""
}

func (x *PublishRequest) GetSignedPrekey() string {
	if x != nil {
		return x.SignedPrekey
	}
	return ""
}

func (x *PublishRequest) GetSignedPrekeySig() string {
	if x != nil {
		return x.SignedPrekeySig
	}
	return ""
}

func (x *PublishRequest) GetPrekeys() []string {
	if x != nil {
		return x.Prekeys
	}
	return nil
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[56]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[56]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{56}
}

func (x *FetchRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FetchRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *KeyBundle) Reset() {
	*x = KeyBundle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[57]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyBundle) ProtoMessage() {}

func (x *KeyBundle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[57]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyBundle.ProtoReflect.Descriptor instead.
func (*KeyBundle) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{57}
}

func (x *KeyBundle) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *KeyBundle) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *KeyBundle) GetIdentityKey() string {
	if x != nil {
		return x.IdentityKey
	}
	return ""
}

func (x *KeyBundle) GetSigningKey() string {
	if x != nil {
		return x.SigningKey
	}
	return ""
}

func (x *KeyBundle) GetSignedPrekey() string {
	if x != nil {
		return x.SignedPrekey
	}
	return ""
}

func (x *KeyBundle) GetSignedPrekeySig() string {
	if x != nil {
		return x.SignedPrekeySig
	}
	return ""
}

func (x *KeyBundle) GetOneTimePrekey() string {
	if x != nil {
		return x.OneTimePrekey
	}
	return ""
}

func (x *FetchReply) Reset() {
	*x = FetchReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[58]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchReply) ProtoMessage() {}

func (x *FetchReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[58]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchReply.ProtoReflect.Descriptor instead.
func (*FetchReply) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{58}
}

func (x *FetchReply) GetBundle() *KeyBundle {
	if x != nil {
		return x.Bundle
	}
	return nil
}

func (x *FetchReply) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *FetchAllReply) Reset() {
	*x = FetchAllReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[59]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchAllReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchAllReply) ProtoMessage() {}

func (x *FetchAllReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[59]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchAllReply.ProtoReflect.Descriptor instead.
func (*FetchAllReply) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{59}
}

func (x *FetchAllReply) GetBundles() []*KeyBundle {
	if x != nil {
		return x.Bundles
	}
	return nil
}

// PublishReply mirrors keydir.State across the service boundary. Publishing used to
// be write-only here, so a gateway talking to a remote keydird could not tell its
// device what the directory now holds -- and nothing else can tell it, because
// one-time prekeys are consumed by PEERS fetching bundles.

func (x *PublishReply) Reset() {
	*x = PublishReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_syncapp_v1_services_proto_msgTypes[60]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishReply) ProtoMessage() {}

func (x *PublishReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_syncapp_v1_services_proto_msgTypes[60]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishReply.ProtoReflect.Descriptor instead.
func (*PublishReply) Descriptor() ([]byte, []int) {
	return file_proto_syncapp_v1_services_proto_rawDescGZIP(), []int{60}
}

func (x *PublishReply) GetOneTimePrekeysLeft() int32 {
	if x != nil {
		return x.OneTimePrekeysLeft
	}
	return 0
}

func (x *PublishReply) GetSignedPrekeyFirstSeenMs() int64 {
	if x != nil {
		return x.SignedPrekeyFirstSeenMs
	}
	return 0
}

func (x *PublishReply) GetAccepted() int32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func file_proto_syncapp_v1_services_proto_rawDescGZIP() []byte {
	file_proto_syncapp_v1_services_proto_rawDescOnce.Do(func() {
		file_proto_syncapp_v1_services_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_syncapp_v1_services_proto_rawDescData)
	})
	return file_proto_syncapp_v1_services_proto_rawDescData
}

func init() { file_proto_syncapp_v1_services_proto_init() }
func file_proto_syncapp_v1_services_proto_init() {
	if File_proto_syncapp_v1_services_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_syncapp_v1_services_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Session); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Chat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ChatMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Attachment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ForwardOrigin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*RegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*LoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*SessionUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*TokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*ResumeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*Identity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*UserIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*SessionRow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*SessionsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*RevokeOwnedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*RevokeAllRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*RevokeAllReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteAccountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*LoginWithCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*ChangePasswordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*ChangePasswordReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[23].Exporter = func(v any, i int) any {
			switch v := v.(*BeginTOTPRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[24].Exporter = func(v any, i int) any {
			switch v := v.(*BeginTOTPReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[25].Exporter = func(v any, i int) any {
			switch v := v.(*ConfirmTOTPRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[26].Exporter = func(v any, i int) any {
			switch v := v.(*ConfirmTOTPReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[27].Exporter = func(v any, i int) any {
			switch v := v.(*DisableTOTPRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[28].Exporter = func(v any, i int) any {
			switch v := v.(*TwoFactorStateReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[29].Exporter = func(v any, i int) any {
			switch v := v.(*DirectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[30].Exporter = func(v any, i int) any {
			switch v := v.(*ChatIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[31].Exporter = func(v any, i int) any {
			switch v := v.(*CreateGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[32].Exporter = func(v any, i int) any {
			switch v := v.(*MembersReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[33].Exporter = func(v any, i int) any {
			switch v := v.(*MemberIDsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[34].Exporter = func(v any, i int) any {
			switch v := v.(*MemberPageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[35].Exporter = func(v any, i int) any {
			switch v := v.(*ChatUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[36].Exporter = func(v any, i int) any {
			switch v := v.(*BoolReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[37].Exporter = func(v any, i int) any {
			switch v := v.(*CountReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[38].Exporter = func(v any, i int) any {
			switch v := v.(*PinnedCountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[39].Exporter = func(v any, i int) any {
			switch v := v.(*UserChatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[40].Exporter = func(v any, i int) any {
			switch v := v.(*UserChatPageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[41].Exporter = func(v any, i int) any {
			switch v := v.(*SetChatFlagsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[42].Exporter = func(v any, i int) any {
			switch v := v.(*ChatFlagsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[43].Exporter = func(v any, i int) any {
			switch v := v.(*ChatSummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[44].Exporter = func(v any, i int) any {
			switch v := v.(*ChatSummariesReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[45].Exporter = func(v any, i int) any {
			switch v := v.(*SubmitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[46].Exporter = func(v any, i int) any {
			switch v := v.(*SubmitReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[47].Exporter = func(v any, i int) any {
			switch v := v.(*HistoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[48].Exporter = func(v any, i int) any {
			switch v := v.(*HistoryReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[49].Exporter = func(v any, i int) any {
			switch v := v.(*ThreadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[50].Exporter = func(v any, i int) any {
			switch v := v.(*ForwardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[51].Exporter = func(v any, i int) any {
			switch v := v.(*MarkReadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[52].Exporter = func(v any, i int) any {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[53].Exporter = func(v any, i int) any {
			switch v := v.(*UserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[54].Exporter = func(v any, i int) any {
			switch v := v.(*TypingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[55].Exporter = func(v any, i int) any {
			switch v := v.(*PublishRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[56].Exporter = func(v any, i int) any {
			switch v := v.(*FetchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[57].Exporter = func(v any, i int) any {
			switch v := v.(*KeyBundle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[58].Exporter = func(v any, i int) any {
			switch v := v.(*FetchReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[59].Exporter = func(v any, i int) any {
			switch v := v.(*FetchAllReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_syncapp_v1_services_proto_msgTypes[60].Exporter = func(v any, i int) any {
			switch v := v.(*PublishReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_syncapp_v1_services_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   61,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_proto_syncapp_v1_services_proto_goTypes,
		DependencyIndexes: file_proto_syncapp_v1_services_proto_depIdxs,
		EnumInfos:         file_proto_syncapp_v1_services_proto_enumTypes,
		MessageInfos:      file_proto_syncapp_v1_services_proto_msgTypes,
	}.Build()
	File_proto_syncapp_v1_services_proto = out.File
	file_proto_syncapp_v1_services_proto_rawDesc = nil
	file_proto_syncapp_v1_services_proto_goTypes = nil
	file_proto_syncapp_v1_services_proto_depIdxs = nil
}
