name: Synapse

options:
  bundleIdPrefix: chat.synapse
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true
  localPackagesGroup: Packages
  transitivelyLinkDependencies: true

configs:
  Dev: debug
  Stage: release
  Prod: release

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    ENABLE_USER_SCRIPT_SANDBOXING: YES
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"

packages:
  Synapse:
    path: .

targets:
  Synapse:
    type: application
    platform: iOS

    sources:
      - path: App

      - path: Resources
        buildPhase: resources

    info:
      path: App/Info.plist

    configFiles:
      Dev: Config/Dev.xcconfig
      Stage: Config/Stage.xcconfig
      Prod: Config/Prod.xcconfig

    dependencies:
      - package: Synapse
        products:
          - SynapseDI
          - SynapsePresentation

    settings:
      base:
        SWIFT_EMIT_LOC_STRINGS: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor

schemes:
  Synapse Dev:
    build:
      targets:
        Synapse: all
    run:
      config: Dev
    test:
      config: Dev

  Synapse Stage:
    build:
      targets:
        Synapse: all
    run:
      config: Stage
    test:
      config: Stage

  Synapse Prod:
    build:
      targets:
        Synapse: all
    run:
      config: Prod
    test:
      config: Prod